### ISSUE TITLE
backup/restore does not honor event order

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#21]
The back/restore mechanism (which exports all events into a flat CSV) sometimes has problems restoring these events when they appear in the CSV file in an order so that at any point the week's sum is negative.

Possible solution: Export events in exactly the order in which they are interpreted by TWT normally (old before new, if timestamp is equal: "out" before "in").

**Comment by mathisdt** [comment]
java.lang.RuntimeException:

 An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:325)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: sum of a week may not be negative
	at org.zephyrsoft.trackworktime.model.Week.setSum(Week.java:65)
	at org.zephyrsoft.trackworktime.timer.TimerManager.updateWeekSum(TimerManager.java:598)
	at org.zephyrsoft.trackworktime.timer.TimerManager.createEvent(TimerManager.java:581)
	at org.zephyrsoft.trackworktime.database.DAO.restoreFromReader(DAO.java:759)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1083)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1068)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.IllegalArgumentException: sum of a week may not be negative
	at org.zephyrsoft.trackworktime.model.Week.setSum(Week.java:65)
	at org.zephyrsoft.trackworktime.timer.TimerManager.updateWeekSum(TimerManager.java:598)
	at org.zephyrsoft.trackworktime.timer.TimerManager.createEvent(TimerManager.java:581)
	at org.zephyrsoft.trackworktime.database.DAO.restoreFromReader(DAO.java:759)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1083)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1068)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by mathisdt** [comment]
A week's sum is not calculated this way anymore.
