### ISSUE TITLE
report generation does not honor event order

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#22]
The report generation mechanism seems to have problems with the order in which events are interpreted if at any time a week's sum is negative. 

Also see #21.

**Comment by mathisdt** [comment]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: sum of a week may not be negative
	at org.zephyrsoft.trackworktime.model.Week.setSum(Week.java:65)
	at org.zephyrsoft.trackworktime.timer.TimerManager.updateWeekSum(TimerManager.java:598)
	at org.zephyrsoft.trackworktime.timer.TimerManager.createEvent(TimerManager.java:581)
	at org.zephyrsoft.trackworktime.database.DAO.restoreFromReader(DAO.java:759)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1036)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1021)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
java.lang.IllegalArgumentException: sum of a week may not be negative
	at org.zephyrsoft.trackworktime.model.Week.setSum(Week.java:65)
	at org.zephyrsoft.trackworktime.timer.TimerManager.updateWeekSum(TimerManager.java:598)
	at org.zephyrsoft.trackworktime.timer.TimerManager.createEvent(TimerManager.java:581)
	at org.zephyrsoft.trackworktime.database.DAO.restoreFromReader(DAO.java:759)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1036)
	at org.zephyrsoft.trackworktime.WorkTimeTrackerActivity$15.doInBackground(WorkTimeTrackerActivity.java:1021)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by mathisdt** [comment]
A week's sum is not calculated this way anymore.
