### ISSUE TITLE
IllegalStateException: "not allowed to start service intent - app is in background" on Android 8+

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#37]
```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.zephyrsoft.trackworktime/.location.LocationTrackerService (has extras) }: app is in background uid UidRecord{fbd005 u0a305 RCVR bg:+4m57s939ms idle procs:2 seq(223,223,223)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
	at android.app.ContextImpl.startService(ContextImpl.java:1484)
	at android.content.ContextWrapper.startService(ContextWrapper.java:663)
	at org.zephyrsoft.trackworktime.Basics.startLocationTrackerService(Basics.java:361)
	at org.zephyrsoft.trackworktime.Basics.checkLocationBasedTracking(Basics.java:341)
	at org.zephyrsoft.trackworktime.Basics.safeCheckLocationBasedTracking(Basics.java:218)
	at org.zephyrsoft.trackworktime.Basics.periodicHook(Basics.java:196)
	at org.zephyrsoft.trackworktime.Watchdog.onReceive(Watchdog.java:34)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3390)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Starting with API level 21 (Android 5.0 Lollipop), the [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) is available and apparently under Oreo it has to be used if the user didn't grant an exception.

Anyone may go to "Settings" -> "Apps & notifications" -> "Advanced" -> "Special app access" -> "Battery optimization", select "All apps", tap on "Track Work Time" in the list and select "Don't optimize". This will exclude TWT from some restrictions regarding background work.

**Comment by mathisdt** [comment]
also see: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by mathisdt** [comment]
It seems that starting the services in the foreground is the better way.
