### ISSUE TITLE
WorkManager crashes

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#96]
Head:  `0160039b6648921f`

AVD: API 29

Stacktrace:
```
2020-05-10 22:01:18.864 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.zephyrsoft.trackworktime:acra, PID: 12229
    java.lang.RuntimeException: Unable to create application org.zephyrsoft.trackworktime.WorkTimeTrackerApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
        at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:146)
        at androidx.work.WorkManager.getInstance(WorkManager.java:181)
        at org.zephyrsoft.trackworktime.WorkTimeTrackerApplication.onCreate(WorkTimeTrackerApplication.java:109)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
```

**Comment by WildOrangutan** [comment]
Seems like it went away after clearing app data and cache 🤷‍♂️
